server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "dTO2gT4P89i85Tiln3Dp/UxDcVqgVO+v6omfgXrsMkoV1k0IWioXcTkg7Zk0HhGQ"
  valid-duration: 3600 # in seconds
  refreshale-duration: 360000 # in seconds